version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_cont
    environment:
      - MYSQL_DATABASE=expenses_tracker 
      - MYSQL_ROOT_PASSWORD=springstudent 
      # - MYSQL_USER=springstudent
    ports:
      - 3306:3306
    networks:
      - exp-app-network
    volumes:
      - exp-vol:/var/lib/mysql/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  myapp:
    build: .
    container_name: exp_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_cont:3306/expenses_tracker
      - SPRING_DATASOURCE_USERNAME=springstudent
      - SPRING_DATASOURCE_PASSWORD=springstudent
    ports:
      - 8080:8080
    networks:
      - exp-app-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  exp-app-network:

volumes:
  exp-vol:

